"""Описания вещей: монстры, предметы, снаряды, декорации.

Кадры взяты по фактическому составу лампов WAD: у «живых» поз есть 8 поворотов,
у кадров смерти — только нулевой поворот.
"""

# ---------------------------------------------------------------- монстры
# walk/attack/pain/death — списки (буква кадра, длительность в секундах, действие)
T = 1.0 / 35.0          # тик DOOM


def seq(letters, tics, action=None):
    return [(c, tics * T, action) for c in letters]


MONSTERS = {
    3004: dict(  # бывший человек
        sprite='POSS', hp=20, radius=20, height=56, speed=78, painchance=200,
        see='DSPOSIT1', pain='DSPOPAIN', death='DSPODTH1', active='DSPOSACT',
        attack='DSPISTOL', melee=None, missile=None, hitscan=(1, 3, 5),
        walk=seq('AABBCCDD', 4),
        atk=[('E', 10 * T, None), ('F', 8 * T, 'hitscan'), ('E', 8 * T, None)],
        hurt=seq('G', 3) + seq('G', 3),
        die=[('H', 5 * T, None), ('I', 5 * T, 'fall'), ('J', 5 * T, None),
             ('K', 5 * T, None), ('L', None, None)],
        gib=[('M', 5 * T, None), ('N', 5 * T, 'fall'), ('O', 5 * T, None),
             ('P', 5 * T, None), ('Q', 5 * T, None), ('R', 5 * T, None),
             ('S', 5 * T, None), ('T', 5 * T, None), ('U', None, None)]),
    9: dict(     # бывший сержант
        sprite='SPOS', hp=30, radius=20, height=56, speed=78, painchance=170,
        see='DSSPOSIT', pain='DSPOPAIN', death='DSPODTH2', active='DSPOSACT',
        attack='DSSHOTGN', melee=None, missile=None, hitscan=(3, 3, 5),
        walk=seq('AABBCCDD', 4),
        atk=[('E', 10 * T, None), ('F', 10 * T, 'hitscan'), ('E', 10 * T, None)],
        hurt=seq('G', 3) + seq('G', 3),
        die=[('H', 5 * T, None), ('I', 5 * T, 'fall'), ('J', 5 * T, None),
             ('K', 5 * T, None), ('L', None, None)],
        gib=[('M', 5 * T, None), ('N', 5 * T, 'fall'), ('O', 5 * T, None),
             ('P', 5 * T, None), ('Q', 5 * T, None), ('R', 5 * T, None),
             ('S', 5 * T, None), ('T', 5 * T, None), ('U', None, None)]),
    3001: dict(  # имп
        sprite='TROO', hp=60, radius=20, height=56, speed=78, painchance=200,
        see='DSBGSIT1', pain='DSPOPAIN', death='DSBGDTH1', active='DSBGACT',
        attack='DSCLAW', melee=(3, 8), missile='BAL1', hitscan=None,
        walk=seq('AABBCCDD', 3),
        atk=[('E', 8 * T, None), ('F', 8 * T, None), ('G', 6 * T, 'attack')],
        hurt=seq('H', 2) + seq('H', 2),
        die=[('I', 8 * T, None), ('J', 8 * T, 'fall'), ('K', 6 * T, None),
             ('L', 6 * T, None), ('M', None, None)],
        gib=[('N', 5 * T, None), ('O', 5 * T, 'fall'), ('P', 5 * T, None),
             ('Q', 5 * T, None), ('R', 5 * T, None), ('S', 5 * T, None),
             ('T', 5 * T, None), ('U', None, None)]),
    3002: dict(  # демон
        sprite='SARG', hp=150, radius=30, height=56, speed=150, painchance=180,
        see='DSSGTSIT', pain='DSDMPAIN', death='DSSGTDTH', active='DSDMACT',
        attack='DSSGTATK', melee=(4, 10), missile=None, hitscan=None,
        walk=seq('AABBCCDD', 2),
        atk=[('E', 8 * T, None), ('F', 8 * T, None), ('G', 8 * T, 'melee')],
        hurt=seq('H', 2) + seq('H', 2),
        die=[('I', 8 * T, None), ('J', 8 * T, 'fall'), ('K', 4 * T, None),
             ('L', 4 * T, None), ('M', 4 * T, None), ('N', None, None)]),
    58: dict(    # спектр (тот же демон, но полупрозрачный — рисуем тускло)
        sprite='SARG', hp=150, radius=30, height=56, speed=150, painchance=180,
        see='DSSGTSIT', pain='DSDMPAIN', death='DSSGTDTH', active='DSDMACT',
        attack='DSSGTATK', melee=(4, 10), missile=None, hitscan=None, shadow=True,
        walk=seq('AABBCCDD', 2),
        atk=[('E', 8 * T, None), ('F', 8 * T, None), ('G', 8 * T, 'melee')],
        hurt=seq('H', 2) + seq('H', 2),
        die=[('I', 8 * T, None), ('J', 8 * T, 'fall'), ('K', 4 * T, None),
             ('L', 4 * T, None), ('M', 4 * T, None), ('N', None, None)]),
    3005: dict(  # какодемон
        sprite='HEAD', hp=400, radius=31, height=56, speed=70, painchance=128,
        see='DSCACSIT', pain='DSDMPAIN', death='DSCACDTH', active=None,
        attack=None, melee=None, missile='BAL2', hitscan=None, float=True,
        walk=seq('A', 3) * 4,
        atk=[('B', 5 * T, None), ('C', 5 * T, None), ('D', 5 * T, 'attack')],
        hurt=seq('E', 3) + seq('F', 6),
        die=[('G', 8 * T, None), ('H', 8 * T, 'fall'), ('I', 8 * T, None),
             ('J', 8 * T, None), ('K', 8 * T, None), ('L', None, None)]),
    3006: dict(  # потерянная душа
        sprite='SKUL', hp=100, radius=16, height=56, speed=230, painchance=256,
        see=None, pain='DSDMPAIN', death='DSFIRXPL', active=None,
        attack='DSSKLATK', melee=(2, 8), missile=None, hitscan=None,
        float=True, bright=True, charge=True,
        walk=seq('AB', 10),
        atk=[('C', 10 * T, None), ('D', 4 * T, 'charge')],
        hurt=seq('E', 3) + seq('E', 3),
        die=[('F', 6 * T, None), ('G', 6 * T, 'fall'), ('H', 6 * T, None),
             ('I', 6 * T, None), ('J', 6 * T, None), ('K', None, None)]),
    3003: dict(  # барон
        sprite='BOSS', hp=1000, radius=24, height=64, speed=90, painchance=50,
        see='DSBRSSIT', pain='DSDMPAIN', death='DSBRSDTH', active='DSDMACT',
        attack='DSCLAW', melee=(10, 8), missile='BAL7', hitscan=None,
        walk=seq('AABBCCDD', 3),
        atk=[('E', 8 * T, None), ('F', 8 * T, None), ('G', 8 * T, 'attack')],
        hurt=seq('H', 2) + seq('H', 2),
        die=[('I', 8 * T, None), ('J', 8 * T, 'fall'), ('K', 8 * T, None),
             ('L', 8 * T, None), ('M', 8 * T, None), ('N', 8 * T, None),
             ('O', None, None)]),
    69: dict(    # рыцарь ада (в freedoom1 может отсутствовать)
        sprite='BOS2', hp=500, radius=24, height=64, speed=90, painchance=50,
        see='DSKNTSIT', pain='DSDMPAIN', death='DSKNTDTH', active='DSDMACT',
        attack='DSCLAW', melee=(10, 8), missile='BAL7', hitscan=None,
        walk=seq('AABBCCDD', 3),
        atk=[('E', 8 * T, None), ('F', 8 * T, None), ('G', 8 * T, 'attack')],
        hurt=seq('H', 2) + seq('H', 2),
        die=[('I', 8 * T, None), ('J', 8 * T, 'fall'), ('K', 8 * T, None),
             ('L', 8 * T, None), ('M', 8 * T, None), ('N', 8 * T, None),
             ('O', None, None)]),
    16: dict(    # кибердемон
        sprite='CYBR', hp=4000, radius=40, height=110, speed=130, painchance=20,
        see='DSCYBSIT', pain='DSDMPAIN', death='DSCYBDTH', active='DSDMACT',
        attack=None, melee=None, missile='MISL', hitscan=None, boss=True,
        walk=seq('AABBCCDD', 3),
        atk=[('E', 12 * T, 'attack'), ('F', 12 * T, 'attack'), ('E', 12 * T, 'attack')],
        hurt=seq('G', 10),
        die=[('H', 10 * T, None), ('I', 10 * T, 'fall'), ('J', 10 * T, None),
             ('K', 10 * T, None), ('L', 10 * T, None), ('M', 10 * T, None),
             ('N', 10 * T, None), ('O', 10 * T, None), ('P', None, None)]),
    7: dict(     # паук-предводитель
        sprite='SPID', hp=3000, radius=100, height=100, speed=110, painchance=40,
        see='DSSPISIT', pain='DSDMPAIN', death='DSSPIDTH', active='DSDMACT',
        attack='DSSHOTGN', melee=None, missile=None, hitscan=(3, 3, 5), boss=True,
        walk=seq('AABBCCDDEEFF', 3),
        atk=[('G', 8 * T, 'hitscan'), ('H', 8 * T, 'hitscan'), ('G', 8 * T, 'hitscan')],
        hurt=seq('I', 3),
        die=[('K', 10 * T, None), ('L', 10 * T, 'fall'), ('M', 10 * T, None),
             ('N', 10 * T, None), ('O', 10 * T, None), ('P', 10 * T, None),
             ('Q', 10 * T, None), ('R', 10 * T, None), ('S', None, None)]),
}

MONSTERS.update({
    65: dict(  # пулемётчик
        sprite='CPOS', hp=70, radius=20, height=56, speed=78, painchance=170,
        see='DSPOSIT2', pain='DSPOPAIN', death='DSPODTH2', active='DSPOSACT',
        attack='DSSHOTGN', melee=None, missile=None, hitscan=(4, 3, 5),
        walk=seq('AABBCCDD', 3),
        atk=[('E', 10 * T, 'hitscan'), ('F', 10 * T, 'hitscan'), ('E', 10 * T, None)],
        hurt=seq('G', 3) + seq('G', 3),
        die=[('H', 5 * T, None), ('I', 5 * T, 'fall'), ('J', 5 * T, None),
             ('K', 5 * T, None), ('L', None, None)],
        gib=[('M', 5 * T, None), ('N', 5 * T, 'fall'), ('O', 5 * T, None),
             ('P', 5 * T, None), ('Q', 5 * T, None), ('R', 5 * T, None),
             ('S', 5 * T, None), ('T', None, None)]),
    84: dict(  # эсэсовец
        sprite='SSWV', hp=50, radius=20, height=56, speed=78, painchance=170,
        see='DSSSSIT', pain='DSPOPAIN', death='DSSSDTH', active='DSPOSACT',
        attack='DSSHOTGN', melee=None, missile=None, hitscan=(3, 3, 5),
        walk=seq('AABBCCDD', 3),
        atk=[('E', 10 * T, None), ('F', 10 * T, 'hitscan'), ('G', 10 * T, 'hitscan')],
        hurt=seq('H', 3) + seq('H', 3),
        die=[('I', 5 * T, None), ('J', 5 * T, 'fall'), ('K', 5 * T, None),
             ('L', 5 * T, None), ('M', 5 * T, None), ('N', None, None)],
        gib=[('O', 5 * T, None), ('P', 5 * T, 'fall'), ('Q', 5 * T, None),
             ('R', 5 * T, None), ('S', 5 * T, None), ('T', 5 * T, None),
             ('U', 5 * T, None), ('V', None, None)]),
    71: dict(  # элементаль боли
        sprite='PAIN', hp=400, radius=31, height=56, speed=70, painchance=128,
        see='DSPESIT', pain='DSPEPAIN', death='DSPEDTH', active='DSDMACT',
        attack=None, melee=None, missile=None, hitscan=None, float=True,
        spawn_soul=True,
        walk=seq('AABBCC', 3),
        atk=[('D', 5 * T, None), ('E', 5 * T, None), ('F', 5 * T, 'soul')],
        hurt=seq('G', 6),
        die=[('H', 8 * T, None), ('I', 8 * T, 'fall'), ('J', 8 * T, None),
             ('K', 8 * T, None), ('L', 8 * T, None), ('M', None, None)]),
    66: dict(  # ревенант
        sprite='SKEL', hp=300, radius=20, height=56, speed=120, painchance=100,
        see='DSSKESIT', pain='DSPOPAIN', death='DSSKEDTH', active='DSSKEACT',
        attack='DSSKEPCH', melee=(6, 8), missile='FATB', hitscan=None,
        walk=seq('AABBCCDDEEFF', 2),
        atk=[('J', 10 * T, None), ('K', 10 * T, 'attack'), ('L', 10 * T, None)],
        hurt=seq('A', 3),
        die=[('M', 7 * T, None), ('N', 7 * T, 'fall'), ('O', 7 * T, None),
             ('P', 7 * T, None), ('Q', None, None)]),
    67: dict(  # манкубус
        sprite='FATT', hp=600, radius=48, height=64, speed=60, painchance=80,
        see='DSMANSIT', pain='DSMNPAIN', death='DSMANDTH', active='DSDMACT',
        attack=None, melee=None, missile='MANF', hitscan=None,
        walk=seq('AABBCC', 4),
        atk=[('D', 10 * T, None), ('E', 10 * T, 'attack'), ('F', 10 * T, None),
             ('G', 10 * T, 'attack'), ('H', 10 * T, None), ('I', 10 * T, 'attack')],
        hurt=seq('J', 3) + seq('J', 3),
        die=[('K', 6 * T, None), ('L', 6 * T, 'fall'), ('M', 6 * T, None),
             ('N', 6 * T, None), ('O', 6 * T, None), ('P', 6 * T, None),
             ('Q', 6 * T, None), ('R', 6 * T, None), ('S', 6 * T, None),
             ('T', None, None)]),
    68: dict(  # арахнотрон
        sprite='BSPI', hp=500, radius=64, height=64, speed=96, painchance=128,
        see='DSBSPSIT', pain='DSDMPAIN', death='DSBSPDTH', active='DSBSPACT',
        attack=None, melee=None, missile='APLS', hitscan=None,
        walk=seq('AABBCCDDEEFF', 3),
        atk=[('G', 10 * T, None), ('H', 8 * T, 'attack'), ('H', 8 * T, 'attack')],
        hurt=seq('I', 3),
        die=[('J', 10 * T, None), ('K', 10 * T, 'fall'), ('L', 10 * T, None),
             ('M', 10 * T, None), ('N', 10 * T, None), ('O', 10 * T, None),
             ('P', None, None)]),
    64: dict(  # архвайл
        sprite='VILE', hp=700, radius=20, height=56, speed=130, painchance=10,
        see='DSVILSIT', pain='DSVIPAIN', death='DSVILDTH', active='DSVILACT',
        attack='DSVILATK', melee=None, missile=None, hitscan=(1, 20, 4),
        walk=seq('AABBCCDDEEFF', 2),
        atk=[('G', 10 * T, None), ('H', 8 * T, None), ('I', 8 * T, 'hitscan'),
             ('J', 8 * T, None)],
        hurt=seq('Q', 5),
        die=[('R', 7 * T, None), ('S', 7 * T, 'fall'), ('T', 7 * T, None),
             ('U', 7 * T, None), ('V', 7 * T, None), ('W', 7 * T, None),
             ('X', 7 * T, None), ('Y', 7 * T, None), ('Z', None, None)]),
})


# ---------------------------------------------------------------- снаряды
MISSILES = {
    'BAL1': dict(sprite='BAL1', speed=600, damage=(3, 8), radius=6, height=8,
                 fly='AB', boom='CDE', sound='DSFIRSHT', hit='DSFIRXPL'),
    'BAL2': dict(sprite='BAL2', speed=600, damage=(5, 8), radius=6, height=8,
                 fly='AB', boom='CDE', sound='DSFIRSHT', hit='DSFIRXPL'),
    'BAL7': dict(sprite='BAL7', speed=900, damage=(8, 8), radius=6, height=8,
                 fly='AB', boom='CDE', sound='DSFIRSHT', hit='DSFIRXPL'),
    'MISL': dict(sprite='MISL', speed=1200, damage=(20, 8), radius=11, height=8,
                 fly='A', boom='BCD', sound='DSRLAUNC', hit='DSBAREXP', splash=128),
    'PLSS': dict(sprite='PLSS', speed=1750, damage=(5, 8), radius=13, height=8,
                 fly='AB', boom='AB', sound='DSPLASMA', hit='DSFIRXPL', bright=True),
    'BFS1': dict(sprite='BFS1', speed=900, damage=(100, 8), radius=13, height=8,
                 fly='AB', boom='ABCDE', sound='DSBFG', hit='DSRXPLOD',
                 splash=256, bright=True),
    'FATB': dict(sprite='FATB', speed=800, damage=(10, 8), radius=11, height=8,
                 fly='AB', boom='ABCDE', boom_sprite='FBXP', sound='DSSKEATK',
                 hit='DSBAREXP', bright=True),
    'MANF': dict(sprite='MANF', speed=700, damage=(8, 8), radius=6, height=8,
                 fly='AB', boom='ABCDE', boom_sprite='FBXP', sound='DSFIRSHT',
                 hit='DSFIRXPL', bright=True),
    'APLS': dict(sprite='APLS', speed=1000, damage=(5, 8), radius=13, height=8,
                 fly='AB', boom='ABCDE', boom_sprite='APBX', sound='DSPLASMA',
                 hit='DSFIRXPL', bright=True),
}

# ---------------------------------------------------------------- предметы
# тип -> (спрайт, вид, значение, сообщение, звук)
ITEMS = {
    2007: ('CLIP', 'ammo_bull', 10, 'обойма', 'DSITEMUP'),
    2048: ('AMMO', 'ammo_bull', 50, 'коробка патронов', 'DSITEMUP'),
    2008: ('SHEL', 'ammo_shell', 4, 'патроны к дробовику', 'DSITEMUP'),
    2049: ('SBOX', 'ammo_shell', 20, 'ящик патронов к дробовику', 'DSITEMUP'),
    2010: ('ROCK', 'ammo_rckt', 1, 'ракета', 'DSITEMUP'),
    2046: ('BROK', 'ammo_rckt', 5, 'ящик ракет', 'DSITEMUP'),
    2047: ('CELL', 'ammo_cell', 20, 'батарея', 'DSITEMUP'),
    17: ('CELP', 'ammo_cell', 100, 'энергоблок', 'DSITEMUP'),
    8: ('BPAK', 'backpack', 0, 'рюкзак с боеприпасами', 'DSITEMUP'),
    2011: ('STIM', 'health', 10, 'стимулятор', 'DSITEMUP'),
    2012: ('MEDI', 'health', 25, 'аптечка', 'DSITEMUP'),
    2014: ('BON1', 'health_bonus', 1, 'бонус здоровья', 'DSITEMUP'),
    2015: ('BON2', 'armor_bonus', 1, 'бонус брони', 'DSITEMUP'),
    2018: ('ARM1', 'armor', 100, 'бронежилет', 'DSITEMUP'),
    2019: ('ARM2', 'armor2', 200, 'мегаброня', 'DSITEMUP'),
    2013: ('SOUL', 'soul', 100, 'СФЕРА ДУШИ!', 'DSGETPOW'),
    2022: ('PINV', 'power_inv', 30, 'НЕУЯЗВИМОСТЬ!', 'DSGETPOW'),
    2023: ('PSTR', 'berserk', 0, 'БЕРСЕРК!', 'DSGETPOW'),
    2024: ('PINS', 'power_invis', 60, 'частичная невидимость', 'DSGETPOW'),
    2025: ('SUIT', 'power_suit', 60, 'защитный костюм', 'DSGETPOW'),
    2026: ('PMAP', 'power_map', 0, 'полная карта', 'DSGETPOW'),
    2045: ('PVIS', 'power_light', 120, 'очки ночного видения', 'DSGETPOW'),
    2001: ('SHOT', 'weapon', 2, 'ДРОБОВИК!', 'DSWPNUP'),
    82: ('SGN2', 'weapon', 8, 'ДВУСТВОЛКА!', 'DSWPNUP'),
    2002: ('MGUN', 'weapon', 3, 'ПУЛЕМЁТ!', 'DSWPNUP'),
    2003: ('LAUN', 'weapon', 4, 'РАКЕТНИЦА!', 'DSWPNUP'),
    2004: ('PLAS', 'weapon', 5, 'ПЛАЗМЕННАЯ ПУШКА!', 'DSWPNUP'),
    2006: ('BFUG', 'weapon', 6, 'BFG9000!', 'DSWPNUP'),
    2005: ('CSAW', 'weapon', 7, 'БЕНЗОПИЛА!', 'DSWPNUP'),
    5: ('BKEY', 'key', 'blue', 'синий ключ-карта', 'DSITEMUP'),
    6: ('YKEY', 'key', 'yellow', 'жёлтый ключ-карта', 'DSITEMUP'),
    13: ('RKEY', 'key', 'red', 'красный ключ-карта', 'DSITEMUP'),
    40: ('BSKU', 'key', 'blue', 'синий череп-ключ', 'DSITEMUP'),
    39: ('YSKU', 'key', 'yellow', 'жёлтый череп-ключ', 'DSITEMUP'),
    38: ('RSKU', 'key', 'red', 'красный череп-ключ', 'DSITEMUP'),
}

# предметы, которые мигают (кадры-анимация покоя)
BLINKING = {2014, 2015, 2018, 2019, 2013, 2022, 2023, 2024, 2026, 2045,
            5, 6, 13, 40, 39, 38}

# бочка взрывается
BARREL = 2035
